include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Consistency
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - require_trailing_commas
    - sort_child_properties_last

    # Quality and safety
    - avoid_print
    - avoid_redundant_argument_values
    - unnecessary_null_checks
    - unnecessary_late

    # Organization
    - directives_ordering
    - sort_pub_dependencies

    # Flutter best practices
    - use_key_in_widget_constructors
    - prefer_const_constructors_in_immutables
