// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAydLUgr-PA6EWsEd38CnLnggoP5IjJLM',
    appId: '1:873227918747:web:ca22d8d2ead92c3a08153e',
    messagingSenderId: '873227918747',
    projectId: 'english-learning-app-4559e',
    authDomain: 'english-learning-app-4559e.firebaseapp.com',
    storageBucket: 'english-learning-app-4559e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAydLUgr-PA6EWsEd38CnLnggoP5IjJLM',
    appId: '1:873227918747:android:ca22d8d2ead92c3a08153e',
    messagingSenderId: '873227918747',
    projectId: 'english-learning-app-4559e',
    storageBucket: 'english-learning-app-4559e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAydLUgr-PA6EWsEd38CnLnggoP5IjJLM',
    appId: '1:873227918747:ios:ca22d8d2ead92c3a08153e',
    messagingSenderId: '873227918747',
    projectId: 'english-learning-app-4559e',
    storageBucket: 'english-learning-app-4559e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAydLUgr-PA6EWsEd38CnLnggoP5IjJLM',
    appId: '1:873227918747:macos:ca22d8d2ead92c3a08153e',
    messagingSenderId: '873227918747',
    projectId: 'english-learning-app-4559e',
    storageBucket: 'english-learning-app-4559e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAydLUgr-PA6EWsEd38CnLnggoP5IjJLM',
    appId: '1:873227918747:windows:ca22d8d2ead92c3a08153e',
    messagingSenderId: '873227918747',
    projectId: 'english-learning-app-4559e',
    storageBucket: 'english-learning-app-4559e.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAAydLUgr-PA6EWsEd38CnLnggoP5IjJLM',
    appId: '1:873227918747:linux:ca22d8d2ead92c3a08153e',
    messagingSenderId: '873227918747',
    projectId: 'english-learning-app-4559e',
    storageBucket: 'english-learning-app-4559e.firebasestorage.app',
  );
}